### ISSUE TITLE
Basic Auth doesn't work due to missing `CryptoJS`

### ISSUE THREAD

**Issue by seanadkinson** [mulesoft/api-designer#217]
Any request with Basic Auth errors out because `CryptoJS` is not defined:

```
TypeError: Cannot read property 'authenticate' of undefined
    at TryIt.execute (http://localhost:9013/bower_components/api-console/dist/scripts/app.js:1632:17)
    at http://localhost:9013/bower_components/angular/angular.js:10821:21
    at http://localhost:9013/bower_components/angular/angular.js:19062:17
    at Scope.$eval (http://localhost:9013/bower_components/angular/angular.js:12658:28)
    at Scope.$apply (http://localhost:9013/bower_components/angular/angular.js:12756:23)
    at HTMLButtonElement.<anonymous> (http://localhost:9013/bower_components/angular/angular.js:19061:21)
    at http://localhost:9013/bower_components/angular/angular.js:2843:10
    at forEach (http://localhost:9013/bower_components/angular/angular.js:325:18)
    at HTMLButtonElement.eventHandler (http://localhost:9013/bower_components/angular/angular.js:2842:5) 
```

[Screenshot here](http://screencast.com/t/8A9LOHittoxk)

Seems like an easy fix to get that dependency in there, but I'm just going to create a fork and merge req that just uses [atob and btoa](https://developer.mozilla.org/en-US/docs/Web/API/window.atob)

**Comment by carowright** [comment]
Already fixed in develop branch. Will be released in next version.
