### ISSUE TITLE
Trying to implement my own "MyFileSystem"

### ISSUE THREAD

**Issue by netwolfuk** [mulesoft/api-designer#335]
Hi, I'm trying to implement a local file store similar to the @brianmc raml-store. There are also some like the fork of raml-store by @arthurtsang

However, when I run a recent copy of dist/ from api-designer's master.zip I am getting the following error. 
```
TypeError: Cannot read property 'slice' of undefined
    at new RamlDirectory (http://localhost:1234/raml-api-designer/dist/scripts/api-designer.js:11091:17)
    at http://localhost:1234/raml-api-designer/dist/scripts/api-designer.js:11184:22
    at processQueue (http://localhost:1234/raml-api-designer/dist/scripts/api-designer-vendor.js:26285:27)
    at http://localhost:1234/raml-api-designer/dist/scripts/api-designer-vendor.js:26301:27
    at Scope.$eval (http://localhost:1234/raml-api-designer/dist/scripts/api-designer-vendor.js:27503:28)
    at Scope.$digest (http://localhost:1234/raml-api-designer/dist/scripts/api-designer-vendor.js:27319:31)
    at Scope.$apply (http://localhost:1234/raml-api-designer/dist/scripts/api-designer-vendor.js:27608:24)
    at done (http://localhost:1234/raml-api-designer/dist/scripts/api-designer-vendor.js:22735:47)
    at completeRequest (http://localhost:1234/raml-api-designer/dist/scripts/api-designer-vendor.js:22925:7)
    at XMLHttpRequest.requestLoaded (http://localhost:1234/raml-api-designer/dist/scripts/api-designer-vendor.js:22866:9)
```

I have tried to remove the requirement to do anything on the server and am therefore just building the data locally.
```javascript
          $http({
            method: 'GET',
            data: '',
            url : '/raml/files',
            withCredentials: false
           }).success(function (data, status, headers, config) {
                 Object.keys(files).forEach(function (key) {
                       delete files[key];
                 });
                 
                 // Don't use the data above. Hack some data together to try and test the data structure.
                 
                 myData = { "files": [
                             { "name" : "fileName.raml",  "path" : "/something/", "type": "file" },
                             { "name" : "fileName2.raml", "path" : "/something/", "type": "file" }
                          ]};
                 
                 Object.keys(myData.files).forEach(function (id) {
                	 files[id] = myData.files[id];
                	 console.log("File id is: " + id);
                	 console.log("File name is: " + files[id].name);
                	 console.log("File path is: " + files[id].path);
                 });
                 deferred.resolve(Object.keys(files));
               })
           .error(deferred.reject.bind(deferred));
```

The code fails at line 11091 of api-designer.js
This is because the path passed into this function is null.
```javascript
      function RamlDirectory(path, meta, contents) {
        // remove the trailing slash to path if it exists
        if (path.slice(-1) === '/' && path.length > 1) {
          path = path.slice(0, -1);
        }
        contents = contents || [];
        this.type = 'directory';
        this.path = path;
        this.name = path.slice(path.lastIndexOf('/') + 1);
        this.meta = meta;
        this.collapsed = true;
        this.isDirectory = true;
        var separated = {
            folder: [],
            file: []
          };
        contents.forEach(function (entry) {
          separated[entry.type || 'file'].push(entry);
        });
        var files = separated.file.filter(notMetaFile).map(function (file) {
            return new RamlFile(file.path, file.contents, {
              dirty: false,
              persisted: true,
              root: file.root
            });
          });
        var directories = separated.folder.map(function (directory) {
            return new RamlDirectory(directory.path, directory.meta, directory.children);
          });
        this.children = directories.concat(files).sort(sortingFunction);
      }
```

**Question**
How do I populate the **files** variable in my javascript, so that RamlDirectory can use it?

FYI. My code is at: https://github.com/tcplugins/tcWebHooks/blob/rest-api-development/tcwebhooks-rest-docs/src/main/webcontent/raml-api-designer/simple-test.html

**Comment by blakeembrey** [comment]
@netwolfuk Your `.directory` function needs to resolve an object that looks like:

```js
{
  path: '/',
  children: [],
  meta: ...
}
```

**Comment by netwolfuk** [comment]
Thank you @blakeembrey 
I've made some good progress now thanks to your pointers.
