### ISSUE TITLE
Missed request module in dependencies.

### ISSUE THREAD

**Issue by FalconIA** [mulesoft/api-designer#478]
Run api-designer@0.4.1 under node@v7.9.0, get an error:

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\FalconIA\AppData\Roaming\npm\node_modules\api-designer\bin\api-designer.js:6:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Then found there no request in dependencies section of `package.json`.

**Comment by agustinlg** [comment]
Its just missing in the package.json? If you install `browser-request` dependency manually it works?

**Comment by FalconIA** [comment]
@agustinlg Yes, it works after installing `request` (not `browser-request`) manually.

**Comment by sichvoge** [comment]
Did you install it via npmjs or from the source code?

**Comment by sichvoge** [comment]
ok that happens with the npmjs only.

**Comment by jraede** [comment]
Still having this issue - seems like it's pretty hot? Any schedule for a fix?

**Comment by davidsonsns** [comment]
To solve the problem quickly, I installed global `npm install -g request`

**Comment by lapo-luchini** [comment]
I worked it around with:

```bash
cd /usr/local/lib/node_modules/api-designer
npm install --save request
```

Would still be nice if `package.json` was fixed on NPM.
