### ISSUE TITLE
Error when run api-designer

### ISSUE THREAD

**Issue by jvargasbdb** [mulesoft/api-designer#518]
Before install api-designer with npm install -g api-designer and run api-designer in console, this genere this error

module.js:540
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jvarg25/.nvm/versions/node/v8.9.4/lib/node_modules/api-designer/bin/api-designer.js:6:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by Northshoot** [comment]
getting same error

**Comment by yegorjke** [comment]
+1

Why is `request` is not a dependency?

**Comment by shisama** [comment]
Package version is old on npmjs.com. Latest is 0.4.13 on master branch.
Try the below command to install the latest version.

```
npm install -g mulesoft/api-designer#master
```

**Comment by carowright** [comment]
Duplicate of #506

**Comment by sapnahargunani** [comment]
None of the above solution is working for me. Keep getting below error:
module.js:340
    throw err;
Could anyone please prove proper set of instructions?
